// <auto-generated/>
#nullable enable
namespace Pochteca;

/// <summary>
/// Provides standard header names used for idempotency, request correlation, and usage echoing.
/// </summary>
public static class HeaderNames
{
    /// <summary>
    /// The header name for idempotency key, used to deduplicate requests.
    /// </summary>
    public const string IdempotencyKey = "Idempotency-Key";

    /// <summary>
    /// The header name for a unique request identifier.
    /// </summary>
    public const string RequestId = "X-Request-Id";

    /// <summary>
    /// The header name for echoing computed usage units.
    /// </summary>
    public const string UsageUnits = "X-Usage-Units";

    /// <summary>
    /// The header name for the category of usage (e.g., billable vs cost).
    /// </summary>
    public const string UsageCategory = "X-Usage-Category";
}

/// <summary>
/// Provides string constants for common usage categories.
/// </summary>
public static class UsageCategories
{
    /// <summary>
    /// Indicates a billable usage event.
    /// </summary>
    public const string Billable = "billable";

    /// <summary>
    /// Indicates an internal cost-only usage event.
    /// </summary>
    public const string Cost = "cost";
}

/// <summary>
/// Schema constants for Pochteca usage events.
/// </summary>
public static class EventSchema
{
    /// <summary>
    /// The version number of the <see cref="Pochteca.UsageEvent"/> schema.
    /// </summary>
    public const int UsageEventVersion = 1;
}
